### ISSUE TITLE
단어를 검색하여 추가할 수 있는 기능 추가

### ISSUE THREAD

**Issue by mwy3055** [mwy3055/MyVoca#103]
**Is your feature request related to a problem? Please describe.**
단어를 일일이 추가하려니 시간이 너무 오래 걸린다. 

**Describe the solution you'd like**
사전에서 단어를 검색하여 추가할 수 있었으면 좋겠다. 예를 들어 영어 단어를 입력하면 뜻을 가져올 수 있어야 한다.

**Describe alternatives you've considered**
이 기능은 꼭 있었으면 좋겠다.

**Additional context**
no

**Comment by mwy3055** [comment]
국립국어원 API로는 영어를 한국어 단어로 검색할 수 없다. 대안으로 네이버 파파고 번역을 시도해 보았으나, 명사조차 동사형으로 번역되는 경향이 있어 사용하지 않기로 결정했다.

**Comment by mwy3055** [comment]
무료 영한사전 API를 찾을 때까지 잠정 중단한다.

**Comment by mwy3055** [comment]
그렇다고 닫을 필요까지는 없잖아?

**Comment by easyhooon** [comment]
웹뷰를 활용하여 단어를 검색하여 추가할 수 있는 기능 추가
