### ISSUE TITLE
상단 바 색깔을 타이틀 바의 색깔과 동일하게 수정

### ISSUE THREAD

**Issue by mwy3055** [mwy3055/MyVoca#142]
**Report which files need refactoring. Provide the absolute path.**
* `ui/structure/MyVocaApp.kt`

**Describe the problem. Summary from Lint Report is welcomed.**

현재 상단 바 색은 `surface`로 디자인되어 있는데, 코드에서 내비게이션 바의 색은 `primary`로 설정되고 있습니다. (36번 라인)

![image](https://github.com/mwy3055/MyVoca/assets/45386920/8446e214-90cc-4623-bece-48a05ce3ce5e)

내비게이션 바의 색깔도 `surface`로 수정해 주세요.

그 외에 다른 화면에서도 내비게이션 바의 색깔이 TopBar와 다른 경우가 없는지 확인해 주세요. (새 디자인 적용 후에)

**Additional context**
no

**Comment by easyhooon** [comment]
새 디자인 적용 후에 모든 화면의 status bar 색상(상단 바) top bar(타이틀 바) 랑 같게 맞췄습니다. 
이슈 종료 해도 될 것 같아요

**Comment by mwy3055** [comment]
확인
