### ISSUE TITLE
하드코딩된 문자열을 string resource로 추출

### ISSUE THREAD

**Issue by mwy3055** [mwy3055/MyVoca#143]
**Report which files need refactoring. Provide the absolute path.**
하드코딩된 string이 있는 모든 파일

**Describe the problem. Summary from Lint Report is welcomed.**
앱에서 사용되는 문자열은 resource로 빼는 것이 좋습니다. 사실 개발 당시에 했어야 했는데, 뭐.. 네...

아래 contentDescription처럼 하드코딩된 문자열을 string resource로 추출해 주세요.
```Kotlin
// Before
Icon(
    imageVector = Icons.Default.Search,
    contentDescription = "Search Icon",
)
```

```Kotlin
// After
Icon(
    imageVector = Icons.Default.Search,
    contentDescription = stringResource(R.string.search_icon_description),
)
```

**Additional context**

[Compose String Resources: Android Developers](https://developer.android.com/jetpack/compose/resources#strings)

**Comment by easyhooon** [comment]
#145

**Comment by easyhooon** [comment]
#146
