### ISSUE TITLE
단어를 삭제했을 때 화면 전체가 깜빡거리는 문제

### ISSUE THREAD

**Issue by easyhooon** [mwy3055/MyVoca#150]
**Describe the bug**
AllWordScreen 에서 단어를 삭제하는 경우(아이템 내에 삭제버튼을 클릭) 전체 화면이 빠르게 어두워졌다가 밝아지면서, 단어가 삭제되고 스낵바가 화면에 출력되는 이슈 

**Additional context**
AllWordScreen 피그마 디자인 반영할 때, 이에 대한 원인을 찾고 해결할 예정

**Comment by easyhooon** [comment]
LoadingIndicator 가 배경 색상이 회색(Gray 0.6f)이어서 발생하는 거 였음...머쓱

**Comment by easyhooon** [comment]
@mwy3055 LoadingIndicator 에 background 속성을 제거하는건 어떨까요? ui 상 깜빡거리는 느낌이 나는것 같아서요

**Comment by mwy3055** [comment]
배경색이 약간은 있어야 터치 불가능한 영역이라는 걸 알릴 수 있을 것 같습니다.

대신 배경색을 회색 말고 하얀색으로 하면 어떤가요? 하얀색에 alpha 0.2f 정도 주면 깜빡이는 느낌은 없을 것 같아요. 

(if 가능하다면) 화면 UiState를 만들 때 처음부터 로딩 상태로 만들면 깜빡임을 아예 없앨 수도 있겠네요

**Comment by easyhooon** [comment]
> 대신 배경색을 회색 말고 하얀색으로 하면 어떤가요? 하얀색에 alpha 0.2f 정도 주면 깜빡이는 느낌은 없을 것 같아요.

좋은 것 같습다. 앞선 두 pr merge 후에 추가 pr로 commit 치겠습니다. detail 한 부분들 수정하는 branch 생성해서

**Comment by easyhooon** [comment]
#156
